FROM docker-registry.usersys.redhat.com/bayesian/cucos-worker
MAINTAINER Slavek Kabrda <slavek@redhat.com>

RUN pip3 install alembic

RUN mkdir -p /f8a_worker
WORKDIR /f8a_worker

ENTRYPOINT ["bash", "-c"]
