FROM docker-registry.usersys.redhat.com/bayesian/cucos-worker
MAINTAINER Tomas Tomecek <ttomecek@redhat.com>

ENV PYTHONDONTWRITEBYTECODE 1

COPY . /cucoslib
WORKDIR /cucoslib
RUN cd tests && pip3 install -r ./requirements.txt

RUN useradd -o -u 1000 -G mock cucos
USER cucos

CMD ["py.test"]
