FROM registry.devshift.net/fabric8-analytics/cucos-worker

ENV PYTHONDONTWRITEBYTECODE 1

COPY . /f8a_worker
RUN cd /f8a_worker/tests && pip3 install -r ./requirements.txt

RUN yum install -y --setopt=tsflags=nodocs mock && yum clean all && \
    useradd -o -u 1000 -G mock f8a
USER f8a
# This is needed for codecov so the CWD is writeable and codecov can write stats to a file.
WORKDIR /tmp

CMD ["py.test", "--cov=/f8a_worker/f8a_worker"]
