FROM registry.devshift.net/bayesian/cucos-worker
MAINTAINER Tomas Tomecek <ttomecek@redhat.com>

ENV PYTHONDONTWRITEBYTECODE 1

COPY . /f8a_worker
WORKDIR /f8a_worker
RUN cd tests && pip3 install -r ./requirements.txt

RUN useradd -o -u 1000 -G mock f8a
USER f8a

CMD ["py.test"]
