"""add index on user_email.

Revision ID: 063c0fcb3fa3
Revises: 097bb617eade
Create Date: 2019-01-03 14:50:28.035928

"""

# revision identifiers, used by Alembic.
revision = '063c0fcb3fa3'
down_revision = '097bb617eade'
branch_labels = None
depends_on = None

from alembic import op


def upgrade():
    """Upgrade the database to a newer revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_api_requests_user_email'), 'api_requests', ['user_email'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade the database to an older revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_requests_user_email'), table_name='api_requests')
    # ### end Alembic commands ###
