"""ading user_id.

Revision ID: 0809bdb23579
Revises: 62010067944d
Create Date: 2020-12-18 15:51:53.133025

"""

# revision identifiers, used by Alembic.
revision = '0809bdb23579'
down_revision = '62010067944d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    """Upgrade the database to a newer revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stack_analyses_request', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_column('stack_analyses_request', 'requestJson')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade the database to an older revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stack_analyses_request', sa.Column('requestJson', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('stack_analyses_request', 'user_id')
    # ### end Alembic commands ###
