"""Add index for synced2graph column

Revision ID: 094ea67a2baf
Revises: 5cf8c7dac1b6
Create Date: 2018-02-21 13:44:20.898452

"""

# revision identifiers, used by Alembic.
revision = '094ea67a2baf'
down_revision = '5cf8c7dac1b6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    """Upgrade the database to a newer revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_synced2graph', 'versions', ['synced2graph'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade the database to an older revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_synced2graph', table_name='versions')
    # ### end Alembic commands ###
