"""add_recommendation_feedack

Revision ID: 0be686aa2297
Revises: 49fb7de6227f  
Create Date: 2018-01-11 10:05:19.423099

"""

# revision identifiers, used by Alembic.
revision = '0be686aa2297'
down_revision = '49fb7de6227f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_feedback',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('stack_id', sa.String(length=64), nullable=False),
                    sa.Column('package_name', sa.String(
                        length=255), nullable=False),
                    sa.Column('recommendation_type', sa.String(
                        length=255), nullable=False),
                    sa.Column('feedback_type', sa.Boolean(), nullable=False),
                    sa.Column('ecosystem', sa.String(
                        length=64), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_feedback')
    # ### end Alembic commands ###
