"""add_col_dep_snapshot

Revision ID: 33b719488061
Revises: da53445aabad
Create Date: 2018-01-30 03:34:01.975834

"""

# revision identifiers, used by Alembic.

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '33b719488061'
down_revision = 'da53445aabad'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade the database to a newer revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stack_analyses_request',
                  sa.Column('dep_snapshot', postgresql.JSONB(
                      astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade the database to an older revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stack_analyses_request', 'dep_snapshot')
    # ### end Alembic commands ###
