"""Removal of anitya

Revision ID: 49fb7de6227f
Revises: 7c643a1823db
Create Date: 2018-01-09 13:51:33.180939

"""

# revision identifiers, used by Alembic.
revision = '49fb7de6227f'
down_revision = '7c643a1823db'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('downstream_map')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downstream_map',
                    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('value', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('key', name='downstream_map_pkey')
                    )
    # ### end Alembic commands ###
