"""add indexes to start and end date for worker_results.

Revision ID: 4bffa8c11eb8
Revises: 063c0fcb3fa3
Create Date: 2019-02-07 08:43:54.376720

"""

# revision identifiers, used by Alembic.
revision = '4bffa8c11eb8'
down_revision = '063c0fcb3fa3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    """Upgrade the database to a newer revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_worker_results_ended_at'), 'worker_results', ['ended_at'], unique=False
    )
    op.create_index(
        op.f('ix_worker_results_started_at'), 'worker_results', ['started_at'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade the database to an older revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_results_started_at'), table_name='worker_results')
    op.drop_index(op.f('ix_worker_results_ended_at'), table_name='worker_results')
    # ### end Alembic commands ###
