"""create user details table.

Revision ID: 661c60224dc8
Revises: 4bffa8c11eb8
Create Date: 2020-05-06 10:54:10.061346

"""

# revision identifiers, used by Alembic.
revision = '661c60224dc8'
down_revision = '4bffa8c11eb8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    """Upgrade the database to a newer revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
                    sa.Column('user_id', sa.String(length=64), nullable=False),
                    sa.Column('snyk_api_token', sa.String(length=64), nullable=True),
                    sa.Column('last_validated_date', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.String(length=32), nullable=True),
                    sa.Column('registered_date', sa.DateTime(), nullable=True),
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('user_source', sa.String(length=32), nullable=True),
                    sa.PrimaryKeyConstraint('user_id'))

    # ### end Alembic commands ###


def downgrade():
    """Downgrade the database to an older revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    # ### end Alembic commands ###
