"""Add column user_id to api_requests table.

Revision ID: 6c7766ceec1c
Revises: 8608c3fa6d42
Create Date: 2021-01-07 15:32:07.211217

"""

# revision identifiers, used by Alembic.
revision = '6c7766ceec1c'
down_revision = '8608c3fa6d42'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    """Upgrade the database to a newer revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_requests', sa.Column(
        'user_id', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade the database to an older revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_requests', 'user_id')
    # ### end Alembic commands ###
