"""Added table component_analyses_requests to store data from CA calls.

Revision ID: 7042ccc96ed4
Revises: 8608c3fa6d42
Create Date: 2021-01-15 14:30:40.497582

"""

# revision identifiers, used by Alembic.
revision = '7042ccc96ed4'
down_revision = '8608c3fa6d42'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    """Upgrade the database to a newer revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_analyses_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ecosystem', sa.String(length=64), nullable=False),
    sa.Column('submit_time', sa.DateTime(), nullable=False),
    sa.Column('stack_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade the database to an older revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_analyses_requests')
    # ### end Alembic commands ###
