"""drop server tables

Revision ID: 750621a9cd89
Revises: 6e7ff4c3177e
Create Date: 2017-03-21 21:26:29.795993

"""

# revision identifiers, used by Alembic.
revision = '750621a9cd89'
down_revision = '6e7ff4c3177e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('permissions_roles')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
                    sa.Column('id', sa.INTEGER(),
                              server_default=sa.text("nextval('role_id_seq'::regclass)"),
                              nullable=False),
                    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False,
                              nullable=True),
                    sa.PrimaryKeyConstraint('id', name='role_pkey'),
                    sa.UniqueConstraint('name', name='role_name_key'),
                    postgresql_ignore_search_path=False)
    op.create_table('user',
                    sa.Column('id', sa.INTEGER(),
                              server_default=sa.text("nextval('user_id_seq'::regclass)"),
                              nullable=False),
                    sa.Column('login', sa.VARCHAR(length=255), autoincrement=False,
                              nullable=True),
                    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False,
                              nullable=True),
                    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False,
                              nullable=True),
                    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False,
                              nullable=True),
                    sa.Column('token_expires', postgresql.TIMESTAMP(), autoincrement=False,
                              nullable=True),
                    sa.PrimaryKeyConstraint('id', name='user_pkey'),
                    sa.UniqueConstraint('login', name='user_login_key'),
                    postgresql_ignore_search_path=False)
    op.create_table('permissions_roles',
                    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'],
                                            name='permissions_roles_permission_id_fkey'),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'],
                                            name='permissions_roles_role_id_fkey'))
    op.create_table('roles_users',
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'],
                                            name='roles_users_role_id_fkey'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                            name='roles_users_user_id_fkey'))
    op.create_table('permission',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='permission_pkey'),
                    sa.UniqueConstraint('name', name='permission_name_key'))
    # ### end Alembic commands ###
