"""three_scale_accounts_table.

Revision ID: 90acd08fb1b4
Revises: 3655e38b92bc
Create Date: 2018-09-27 13:54:30.553412

"""

# revision identifiers, used by Alembic.
revision = '90acd08fb1b4'
down_revision = '3655e38b92bc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    """Upgrade the database to a newer revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_three_scale_accounts',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('account_name', sa.String(length=255), nullable=False),
                    sa.Column('account_secret', sa.String(length=64), nullable=False),
                    sa.Column('admin_id', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade the database to an older revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorized_three_scale_accounts')
    # ### end Alembic commands ###
