"""gemini_model.py

Revision ID: 967036f90ba1
Revises: 094ea67a2baf
Create Date: 2018-02-27 11:15:29.518284

"""

# revision identifiers, used by Alembic.
revision = '967036f90ba1'
down_revision = '094ea67a2baf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osio_registered_repo',
    sa.Column('git_url', sa.String(length=255), nullable=False),
    sa.Column('git_sha', sa.String(length=255), nullable=False),
    sa.Column('email_ids', sa.String(length=255), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('git_sha')
    )
    op.create_index(op.f('ix_versions_synced2graph'), 'versions', ['synced2graph'], unique=False)
    op.drop_index('ix_synced2graph', table_name='versions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_synced2graph', 'versions', ['synced2graph'], unique=False)
    op.drop_index(op.f('ix_versions_synced2graph'), table_name='versions')
    op.drop_table('osio_registered_repo')
    # ### end Alembic commands ###
