"""Do not index ecosystem URL

Revision ID: a60f15a395e2
Revises: 01404498814b
Create Date: 2017-05-22 11:26:17.063282

"""

# revision identifiers, used by Alembic.
revision = 'a60f15a395e2'
down_revision = '01404498814b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ecosystems_url', table_name='ecosystems')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ecosystems_url', 'ecosystems', ['url'], unique=False)
    # ### end Alembic commands ###
