"""probable_cves.

Revision ID: d56a64846a45
Revises: 4bffa8c11eb8
Create Date: 2019-03-06 12:17:20.522771

"""

# revision identifiers, used by Alembic.
revision = 'd56a64846a45'
down_revision = '4bffa8c11eb8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    """Upgrade the database to a newer revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probable_cves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('repository', sa.String(length=100), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('package', sa.String(length=500), nullable=False),
    sa.Column('cause_type', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('issue_url', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fixed_date', sa.DateTime(), nullable=True),
    sa.Column('fixed_url', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('commit_date', sa.DateTime(), nullable=True),
    sa.Column('commit_url', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('identified_date', sa.DateTime(), nullable=True),
    sa.Column('identified_url', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('files_changed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_status', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=25), nullable=True),
    sa.Column('review_comments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flagged_score', sa.String(length=25), nullable=False),
    sa.Column('flagged_at', sa.DateTime(), nullable=False),
    sa.Column('flagged_comments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cve_id', sa.String(length=64), nullable=True),
    sa.Column('cve_date', sa.DateTime(), nullable=True),
    sa.Column('additional_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade the database to an older revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('probable_cves')
    # ### end Alembic commands ###
