"""Added table component_analyses_requests to store data from CA calls.

Revision ID: de5a6b5caef5
Revises: 8608c3fa6d42
Create Date: 2021-01-19 15:20:31.404604

"""

# revision identifiers, used by Alembic.
revision = 'de5a6b5caef5'
down_revision = '8608c3fa6d42'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    """Upgrade the database to a newer revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_analyses_requests',
                    sa.Column('component_analyses_request_id', sa.Integer(), nullable=False),
                    sa.Column('request_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('manifest_hash', sa.String(length=256), nullable=True),
                    sa.Column('ecosystem', sa.String(length=64), nullable=False),
                    sa.Column('submit_time', sa.DateTime(), nullable=False),
                    sa.Column('stack_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
                    sa.Column('user_agent', sa.String(length=256), nullable=False),
                    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.PrimaryKeyConstraint('component_analyses_request_id'))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade the database to an older revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_analyses_requests')
    # ### end Alembic commands ###
