"""Upstream URL can be null

Revision ID: e2762a61d34c
Revises: f5c853b83d41
Create Date: 2017-07-31 08:41:39.811488

"""

# revision identifiers, used by Alembic.
revision = 'e2762a61d34c'
down_revision = 'f5c853b83d41'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_requests', 'api_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('api_requests', 'request_digest',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('monitored_upstreams', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitored_upstreams', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('api_requests', 'request_digest',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('api_requests', 'api_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
